---
stages:
  - welcome
  - test

welcome:
  jobs:
    - sayhello

sayhello:
  script:
    - echo "Hello world"

test:
  jobs:
    - linting
    - pytest

linting:
  artifacts:
    paths:
      - testfile
  script:
    - pylint simpleci
    - touch testfile

pytest:
  inside_docker:
    image: ubuntu
    path: /
  script:
    - cat /etc/os-release
    - ls
    - mkdir IAmANewFolder
    - ls | grep Folder
