---
stages:
  - welcome
  - test

welcome:
  jobs:
    - sayhello

sayhello:
  script:
    - echo "Hello world"

test:
  jobs:
    - pytest
    - linting

linting:
  script:
    - pylint simpleci

pytest:
  inside_docker:
    image: ubuntu
    path: /
  artifacts:
    paths:
      - release_file
  script:
    - cp /etc/os-release release_file
    - uname -r
