---
inside_docker:
  image: debian
  path: /
stages:
  - welcome
  - test

welcome:
  jobs:
    - sayhello

sayhello:
  script:
    - echo "Hello world"

test:
  inside_docker:
    image: archlinux
    path: /
  jobs:
    - pytest
    - linting

linting:
  script:
    - cat /etc/os-release
    - pylint simpleci || true

pytest:
  inside_docker:
    image: ubuntu
    path: /
  artifacts:
    paths:
      - release_file
  script:
    - cp /etc/os-release release_file
    - uname -r
